### PR TITLE
Packages edt themes backups

### PR DESCRIPTION
**Pull request by RolandHughes**
It's time to see if all of these changes can be merged into the base. I created a blog post to include all of the information.

https://www.logikalsolutions.com/wordpress/information-technology/diamond-editor-pull-request/

At that link are also Debians built on Ubuntu 18.04 and 20.04 along with an RPM built on Fedora 33. I had to cheat dumping everything into a diamond directory under /opt on both architectures, then creating a symbolic link from the executable path along with post install process (automated as part of the install) copying .desktop to proper location. I was going to try to create a Snap too, but all of the instructions wanted it to be done on the repository system and direct pushed into Snap store. Out of scope. 

Creating proper Debian and RPM packages for CopperSpice itself was also out of scope. Having the packages wouldn't make the install easier because they wouldn't be in distribution repos.

Need to see if this can be accepted into the Diamond project or if I need to create my own project. 

I created a clean branch and took the tip of the files from diamond-themes branch. This got rid of hundreds and hundreds of check-in history things.

Besides some sweeping coding changes, a big focus of this effort was to make Diamond a warm and friendly project for non-experts. They definitely have the most time to contribute and with proper tutorial documentation they aren't even a tiny burden.

### CODE REVIEW

**Comment by bgeller** [comment]
This is a very large commit and it will take a week to review. We need to verify the coding style conforms to our existing standard and  if the semantic changes are correct.  I do like the idea of adding a backup feature. 

We are currently working on some major enhancements with DoxyPress so looking at your work will most likely happen  towards the end of this month. 

Thanks.

**Comment by RolandHughes** [comment]
[ Edited for clarity with off topic content removed ]

When I asked about a coding style there wasn't one. The .astylerc file 
that I included is from several different client sites that all use the 
BARR group coding standard.  [deleted]

Yes, it is a massive check-in. Next iteration needs to have a completely custom
QPlainTextEdit class build from the existing class source and hidden source.  The
syntax highlighting can be dramatically more efficient as well. On initial load you
only need to highlight the visible window and one "page" on either side of it.

Really want a "persistent" feature too. Every buffer and every position 
saved, not just the ones connected to files.

One of the biggest things is all of the Help/doc needs to be 
internalized. This is so the editor can be used on secured networks 
where Internet access doesn't exist. Medical device companies have a lot 
of those anymore.

later

Roland Hughes

**Comment by bgeller** [comment]
Keeping this very short. Several months ago when you asked for a copy of our style guide we did provide a PDF.  This is a guide our team has developed with the intention of using it on every CS library and application.

**Comment by RolandHughes** [comment]
I don't remember ever receiving it or hearing about it. Not saying you 
didn't mention it, just saying I have no memory of it. Life has been 
busy though.

Roland Hughes

**Pull request closed without merging**
